name: MCkotlin CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build MCkotlin
        run: ./gradlew build
      - name: Upload MCkotlin
        uses: actions/upload-artifact@v4
        with:
          name: "MCKotlin"
          path: "build/libs/"